<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ressources\app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ressources\app_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="doc\MLD.simp.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlBackup.NET.MySqlConnector" Version="2.6.5" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\beehives\ListBeehivePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\beehives\SaveBeehivePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\productsTypes\ListProductTypePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\productsTypes\SaveProductTypePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\localizations\" />
    <Folder Include="src\errors\" />
    <Folder Include="src\configurations\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ressources\invoice_pdf_logo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ressources\appconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
