using Mams_App.src.clients;
using Mams_App.src.entities;
using Mams_App.src.localizations;
using Mams_App.src.receipts;
using Mams_App.src.users;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace Mams_App.src.invoices;

/// <summary>
/// Defines the structure and appearance of profit invoice PDFs generated by the application.
/// This class handles the visual layout, content formatting, and data presentation for profit invoices.
/// In this template, the User (app owner) is the seller and the Entity is the client.
/// </summary>
public class InvoiceProfitTemplate : IDocument
{
    private readonly EntityModel _m_entity_model = new();
    private readonly ClientModel _m_client_model = new();
    private readonly UserModel _m_user_model = new();

    private static string _m_company_logo_path => Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory,
        "resources",
        "invoice_pdf_logo.jpg"
    );

    private ReceiptHandlerItem _m_receipt_item { get; set; }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
    public DocumentSettings GetSettings() => DocumentSettings.Default;

    /// <summary>
    /// Initializes a new instance of the InvoiceProfitTemplate class with receipt information.
    /// </summary>
    /// <param name="receipt_item">Receipt data containing all information needed to generate the invoice.</param>
    public InvoiceProfitTemplate(ReceiptHandlerItem receipt_item)
    {

        // QuestPDF licence NEED to be present
        QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;

        _m_receipt_item = receipt_item;
    }

    /// <summary>
    /// Defines the structure and layout of the invoice document.
    /// Is automatically called when the PDF is generated.
    /// </summary>
    /// <param name="container">The container to compose the document within.</param>
    public void Compose(IDocumentContainer container)
    {
        container
            .Page(page =>
            {
                page.Margin(50);

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);

                page.Footer().AlignCenter().Text(text =>
                {
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
            });
    }

    /// <summary>
    /// Composes the header section of the invoice, including the invoice number, date, and company logo if available.
    /// </summary>
    /// <param name="container">The container to compose the header within.</param>
    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column
                    .Item().Text(Loc.Get("Invoice.Title", _m_receipt_item.receipt_item.receipt_number))
                    .FontSize(20).SemiBold().FontColor(Colors.Blue.Medium);

                column.Item().Text(text =>
                {
                    text.Span(Loc.Get("Invoice.SaleDate")).SemiBold();
                    text.Span($"{_m_receipt_item.receipt_item.receipt_date_created:d}");
                });
            });

            // To avoid a crash if the image path is null or empty
            if (!string.IsNullOrWhiteSpace(_m_company_logo_path))
            {
                row.ConstantItem(75).Image(_m_company_logo_path);
            }
        });
    }

    /// <summary>
    /// Composes the main content section of the invoice, including sender/recipient information,
    /// item details, and total amount.
    /// </summary>
    /// <param name="container">The container to compose the content within.</param>
    private void ComposeContent(IContainer container)
    {

        container.PaddingVertical(40).Column(column =>
        {
            column.Spacing(20);

            column.Item().Row(row =>
            {

                var client_result = _m_client_model.getItemByID(_m_receipt_item.receipt_client_item.fk_client_id.ToString());
                if (!client_result.is_found)
                {
                    return;
                }

                EntityItem? entity_client_item = new();

                // Get the user (app owner) information from the users table
                var user_result = _m_user_model.getUser();
                EntityItem entity_me_item = new();
                if (user_result.is_found && user_result.returned_item != null)
                {
                    // Convert UserItem to EntityItem for InvoiceAddress compatibility
                    entity_me_item = new EntityItem
                    {
                        entity_name = user_result.returned_item.user_name,
                        entity_phone = user_result.returned_item.user_phone,
                        entity_email = user_result.returned_item.user_email,
                        entity_city = user_result.returned_item.user_city,
                        entity_address = user_result.returned_item.user_address
                    };
                }

                entity_client_item = _m_entity_model.getItemByID(client_result.returned_item!.fk_entity_id.ToString()).returned_item;

                row.RelativeItem().Component(new InvoiceAddress(Loc.Get("Invoice.From"), entity_me_item));
                row.ConstantItem(50);
                row.RelativeItem().Component(new InvoiceAddress(Loc.Get("Invoice.To"), entity_client_item ?? new EntityItem()));
            });

            column.Item().Element(ComposeTable);

            var total_price = _m_receipt_item.receipt_product_items.Sum(x => x.receipt_product_unity_price * x.receipt_product_quantity);
            column.Item().PaddingRight(5).AlignRight().Text(Loc.Get("Invoice.FinalTotal", total_price.ToString("C"))).SemiBold();
        });
    }

    /// <summary>
    /// Composes the table section of the invoice displaying the products purchased, 
    /// with their unit prices, quantities, and subtotals.
    /// </summary>
    /// <param name="container">The container to compose the table within.</param>
    private void ComposeTable(IContainer container)
    {
        var header_style = TextStyle.Default.SemiBold();

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.ConstantColumn(25);     // #
                columns.RelativeColumn(3);      // Produit
                columns.RelativeColumn();       // Lot
                columns.RelativeColumn();       // Prix unité
                columns.RelativeColumn();       // Quantité
                columns.RelativeColumn();       // Total
            });

            table.Header(header =>
            {
                header.Cell().Text(Loc.Get("Invoice.Column.Number"));
                header.Cell().Text(Loc.Get("Invoice.Column.Product")).Style(header_style);
                header.Cell().Text(Loc.Get("Invoice.Column.Lot")).Style(header_style);
                header.Cell().AlignRight().Text(Loc.Get("Invoice.Column.UnitPrice")).Style(header_style);
                header.Cell().AlignRight().Text(Loc.Get("Invoice.Column.Quantity")).Style(header_style);
                header.Cell().AlignRight().Text(Loc.Get("Invoice.Column.Total")).Style(header_style);

                header.Cell().ColumnSpan(6).PaddingTop(5).BorderBottom(1).BorderColor(Colors.Black);
            });

            foreach (var item in _m_receipt_item.receipt_product_items)
            {
                var index = _m_receipt_item.receipt_product_items.IndexOf(item) + 1;

                table.Cell().Element(CellStyle).Text($"{index}");
                table.Cell().Element(CellStyle).Text(item.product_item.product_name);
                table.Cell().Element(CellStyle).Text(item.product_lot_item.product_lot_name);
                table.Cell().Element(CellStyle).AlignRight().Text($"{item.receipt_product_unity_price:C}");
                table.Cell().Element(CellStyle).AlignRight().Text($"{item.receipt_product_quantity}");
                table.Cell().Element(CellStyle).AlignRight().Text($"{item.receipt_product_unity_price * item.receipt_product_quantity:C}");

                static IContainer CellStyle(IContainer container) => container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
            }
        });
    }
}