<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net9.0-windows</TargetFramework>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
  <UseWPF>true</UseWPF>
  <ApplicationIcon>resources\app_icon.ico</ApplicationIcon>
    
  <!-- Application Info -->
  <Product>Mams</Product>
  <Company>ThJo</Company>
  <Authors>ThJo</Authors>
</PropertyGroup>

  <ItemGroup>
    <Compile Remove=".github\**" />
    <EmbeddedResource Remove=".github\**" />
    <None Remove=".github\**" />
    <Page Remove=".github\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources\app_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="resources\localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="doc\MLD.simp.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlBackup.NET.MySqlConnector" Version="2.6.5" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\beehives\ListBeehivePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\beehives\SaveBeehivePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\productsTypes\ListProductTypePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\productsTypes\SaveProductTypePage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="resources\invoice_pdf_logo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="resources\version.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Copy init.sql to resources folder in output -->
  <ItemGroup>
    <None Update="database\init.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>resources\init.sql</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="src\search\filters\" />
  </ItemGroup>

</Project>
